### ISSUE TITLE
Waterdrop 2.6.0 Upgrade RSpec Error

### ISSUE THREAD

**Issue by hunzinker** [karafka/waterdrop#355]
Hi - after upgrading `waterdrop` from `2.5.3` -> `2.6.0` I receive a `karafka-testing` error:
```
An error occurred while loading spec_helper.
Failure/Error: require "karafka/testing/rspec/helpers"

NameError:
  uninitialized constant WaterDrop::Producer::DummyClient
# /gems/ruby/3.2.0/gems/karafka-testing-2.1.1/lib/karafka/testing/spec_producer_client.rb:6:in `<module:Testing>'
# /gems/ruby/3.2.0/gems/karafka-testing-2.1.1/lib/karafka/testing/spec_producer_client.rb:4:in `<module:Karafka>'
# /gems/ruby/3.2.0/gems/karafka-testing-2.1.1/lib/karafka/testing/spec_producer_client.rb:3:in `<top (required)>'
# /gems/ruby/3.2.0/gems/zeitwerk-2.6.8/lib/zeitwerk/kernel.rb:38:in `require'
# /gems/ruby/3.2.0/gems/zeitwerk-2.6.8/lib/zeitwerk/kernel.rb:38:in `require'
# /gems/ruby/3.2.0/gems/karafka-testing-2.1.1/lib/karafka/testing/rspec/helpers.rb:6:in `<top (required)>'
# ./spec/spec_helper.rb:17:in `require'
# ./spec/spec_helper.rb:17:in `<top (required)>'
No examples found.
```

Karafka Gems:
```
    karafka (2.1.4)
      karafka-core (>= 2.0.13, < 3.0.0)
      thor (>= 0.20)
      waterdrop (>= 2.5.3, < 3.0.0)
      zeitwerk (~> 2.3)
    karafka-core (2.0.13)
      concurrent-ruby (>= 1.1)
      karafka-rdkafka (>= 0.12.3)
    karafka-rdkafka (0.12.3)
      ffi (~> 1.15)
      mini_portile2 (~> 2.6)
      rake (> 12)
    karafka-testing (2.1.1)
      karafka (>= 2.1.0, < 3.0.0)
    karafka-web (0.6.0)
      erubi (~> 1.4)
      karafka (>= 2.1.4, < 3.0.0)
      karafka-core (>= 2.0.13, < 3.0.0)
      roda (~> 3.68, >= 3.68)
      tilt (~> 2.0)
```

Downgrading `waterdrop` to `2.5.3` fixes the error.

**Comment by mensfeld** [comment]
ref: https://github.com/karafka/karafka-testing/issues/145

fixed in karafka-testing `2.1.2`: https://my.diffend.io/gems/karafka-testing/2.1.1/2.1.2#d2h-662436-967
