### ISSUE TITLE
Errors raised during `produce_sync` and `produce_async` via monitor missing root cause.

### ISSUE THREAD

**Issue by konalegi** [karafka/waterdrop#370]
Big thanks for the gem and all your hard work!

The Producer `#produce_sync` and `#produce_async` methods are missing `error.cause` if they are catched by monitor.
code to reproduce 
```ruby
require 'bundler/inline'

gemfile do
  source 'https://rubygems.org'
  gem 'waterdrop', '~> 2.6'
end

require 'waterdrop'
require 'logger'

PRODUCER = WaterDrop::Producer.new do |config|
  config.kafka = { 'bootstrap.servers': '127.0.0.1:9092'}
  config.logger = Logger.new('/dev/null')
end

PRODUCER.monitor.subscribe('error.occurred') do |event|
  p [event[:type], event[:error], event[:error].cause]
end

PRODUCER.produce_sync({payload: 'Test',topic: "test-topic"})
```

going to generate the following output 
```
["librdkafka.error", #<Rdkafka::RdkafkaError: Local: Broker transport failure (transport)>, nil]
["librdkafka.error", #<Rdkafka::RdkafkaError: Local: All broker connections are down (all_brokers_down)>, nil]
["librdkafka.error", #<Rdkafka::RdkafkaError: Local: Broker transport failure (transport)>, nil]
["message.produce_sync", #<WaterDrop::Errors::ProduceError: #<Rdkafka::AbstractHandle::WaitTimeoutError: Waiting for delivery timed out after 5 seconds>>, nil]
/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/waterdrop-2.6.4/lib/waterdrop/producer/sync.rb:40:in `rescue in produce_sync': #<Rdkafka::AbstractHandle::WaitTimeoutError: Waiting for delivery timed out after 5 seconds> (WaterDrop::Errors::ProduceError)
	from /.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/waterdrop-2.6.4/lib/waterdrop/producer/sync.rb:18:in `produce_sync'
	from waterdrop-missing-error-cause.rb:20:in `<main>'
/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/karafka-rdkafka-0.13.3/lib/rdkafka/abstract_handle.rb:54:in `block in wait': Waiting for delivery timed out after 5 seconds (Rdkafka::AbstractHandle::WaitTimeoutError)
	from /.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/karafka-rdkafka-0.13.3/lib/rdkafka/abstract_handle.rb:51:in `loop'
	from /.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/karafka-rdkafka-0.13.3/lib/rdkafka/abstract_handle.rb:51:in `wait'
	from /.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/waterdrop-2.6.4/lib/waterdrop/producer.rb:193:in `wait'
	from /.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/waterdrop-2.6.4/lib/waterdrop/producer/sync.rb:27:in `block in produce_sync'
	from /.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/karafka-core-2.1.1/lib/karafka/core/monitoring/notifications.rb:118:in `measure_time_taken'
	from /.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/karafka-core-2.1.1/lib/karafka/core/monitoring/notifications.rb:94:in `instrument'
	from /.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/karafka-core-2.1.1/lib/karafka/core/monitoring/monitor.rb:34:in `instrument'
	from /.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/waterdrop-2.6.4/lib/waterdrop/producer/sync.rb:22:in `produce_sync'
	from waterdrop-missing-error-cause.rb:20:in `<main>'
```
I suppose it happens because [here](https://github.com/karafka/waterdrop/blob/master/lib/waterdrop/producer/sync.rb#L30-L38)
the cause is not assigned before sending it to monitor. 

Thanks!

**Comment by mensfeld** [comment]
Indeed. If:

- you need the cause now, please use the `#message` that should have the original cause inspect
- you need this fix fast submit a PR
- you don't need it fast please wait as I am on a holiday :)

**Comment by konalegi** [comment]
I'll provide a PR :)
