### ISSUE TITLE
Wait timeout bypassed on unreachable cluster

### ISSUE THREAD

**Issue by Aerdayne** [karafka/waterdrop#502]
It appears that a transactional producer hangs indefinitely in case it can't connect to the Kafka cluster. In comparison, a non-transactional producer raises an exception after the timeout.

Here's a reproduction script that should be ran against the current main branch.

OS: Darwin Kernel Version 22.6.0

**librdkafka version: 2.1.1_1**

Kafka was ran via WaterDrop's compose file locally.

```ruby
#!/usr/bin/env ruby

require 'bundler/inline'

gemfile do
  source 'https://rubygems.org'

  gem 'waterdrop', path: '.'
  gem 'karafka' # Admin API
end

require 'prettyprint'
require 'securerandom'

topic = SecureRandom.hex(10)

max_message_bytes = 128
max_payload_size = 256

Karafka::App.setup do |karafka_config|
  karafka_config.kafka = {
    'bootstrap.servers': '0.0.0.0:9092'
  }
  karafka_config.max_wait_time = 500
  karafka_config.client_id = SecureRandom.alphanumeric(10)
end

Karafka::Admin.create_topic(topic, 1, 1, { 'max.message.bytes': max_message_bytes })

at_exit do
  Karafka::Admin.delete_topic(topic)
end

producer = ::WaterDrop::Producer.new do |wd_config|
  wd_config.id = SecureRandom.hex(6)
  wd_config.deliver = true

  # The specified URL must be unavailable for reproduction
  wd_config.kafka[:'bootstrap.servers'] = '0.0.0.0:29092'
  wd_config.kafka[:'transactional.id'] = SecureRandom.hex(6)
  wd_config.kafka[:'max.in.flight'] = 5
  wd_config.kafka[:'enable.idempotence'] = true

  wd_config.max_wait_timeout = 10_000
  wd_config.max_payload_size = max_payload_size
end

producer.monitor.subscribe(WaterDrop::Instrumentation::LoggerListener.new(Logger.new(STDOUT)))

thread_lister = Thread.new do
  Thread.current.name = 'Thread lister'

  loop do
    sleep(3)

    puts "\n#{'~' * 80}\nThreads:\n"
    Thread.list.each do |t|
      pp "#{t.inspect} #{t.backtrace.first}"
    end
    puts "#{'~' * 80}\n\n"
  end
end

at_exit do
  thread_lister.kill
end

# Hangs indefinitely, never raises and never exits
begin
  producer.produce_many_sync([{ topic:, payload: 'a' }])
rescue StandardError => e
  puts "\n#{'=' * 80}\nRaised:\n#{e.inspect}\n#{'=' * 80}\n\n"
end
```

Output:

```
E, [2024-06-06T12:57:13.880700 #21245] ERROR -- : [c032477da049] Error occurred: Local: Broker transport failure (transport) - librdkafka.error
E, [2024-06-06T12:57:13.880776 #21245] ERROR -- : rdkafka: [thrd:0.0.0.0:29092/bootstrap]: 0.0.0.0:29092/bootstrap: Connect to ipv4#0.0.0.0:29092 failed: Connection refused (after 0ms in state CONNECT)
E, [2024-06-06T12:57:13.880825 #21245] ERROR -- : [c032477da049] Error occurred: Local: All broker connections are down (all_brokers_down) - librdkafka.error
E, [2024-06-06T12:57:14.386930 #21245] ERROR -- : rdkafka: [thrd:0.0.0.0:29092/bootstrap]: 0.0.0.0:29092/bootstrap: Connect to ipv4#0.0.0.0:29092 failed: Connection refused (after 0ms in state CONNECT, 1 identical error(s) suppressed)
E, [2024-06-06T12:57:14.387028 #21245] ERROR -- : [c032477da049] Error occurred: Local: Broker transport failure (transport) - librdkafka.error

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Threads:
"#<Thread:0x00000001001eb0d0 sleep> /Users/dan/.asdf/installs/ruby/3.2.1/lib/ruby/gems/3.2.0/gems/karafka-rdkafka-0.15.1/lib/rdkafka/producer.rb:144:in `rd_kafka_init_transactions'"
"#<Thread:0x0000000105658d48@FFI Callback Dispatcher sleep> "
"#<Thread:0x00000001073e2da0@Thread lister reprotwo.rb:61 run> reprotwo.rb:69:in `backtrace'"
"#<Thread:0x000000010738f538@rdkafka.native_kafka#waterdrop#producer-3 /Users/dan/.asdf/installs/ruby/3.2.1/lib/ruby/gems/3.2.0/gems/karafka-rdkafka-0.15.1/lib/rdkafka/native_kafka.rb:50 sleep> /Users/dan/.asdf/installs/ruby/3.2.1/lib/ruby/gems/3.2.0/gems/karafka-rdkafka-0.15.1/lib/rdkafka/native_kafka.rb:53:in `rd_kafka_poll'"
"#<Thread:0x000000010738ef98 /Users/dan/.asdf/installs/ruby/3.2.1/lib/ruby/gems/3.2.0/gems/karafka-rdkafka-0.15.1/lib/rdkafka/config.rb:42 sleep_forever> <internal:thread_sync>:18:in `pop'"
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Threads:
"#<Thread:0x00000001001eb0d0 sleep> /Users/dan/.asdf/installs/ruby/3.2.1/lib/ruby/gems/3.2.0/gems/karafka-rdkafka-0.15.1/lib/rdkafka/producer.rb:144:in `rd_kafka_init_transactions'"
"#<Thread:0x0000000105658d48@FFI Callback Dispatcher sleep> "
"#<Thread:0x00000001073e2da0@Thread lister reprotwo.rb:61 run> reprotwo.rb:69:in `backtrace'"
"#<Thread:0x000000010738f538@rdkafka.native_kafka#waterdrop#producer-3 /Users/dan/.asdf/installs/ruby/3.2.1/lib/ruby/gems/3.2.0/gems/karafka-rdkafka-0.15.1/lib/rdkafka/native_kafka.rb:50 sleep> /Users/dan/.asdf/installs/ruby/3.2.1/lib/ruby/gems/3.2.0/gems/karafka-rdkafka-0.15.1/lib/rdkafka/native_kafka.rb:53:in `rd_kafka_poll'"
"#<Thread:0x000000010738ef98 /Users/dan/.asdf/installs/ruby/3.2.1/lib/ruby/gems/3.2.0/gems/karafka-rdkafka-0.15.1/lib/rdkafka/config.rb:42 sleep_forever> <internal:thread_sync>:18:in `pop'"
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

... and so on
```

Additionally, as the reproduction script runs, more and more `rdkafka.native_kafka#waterdrop#producer-X` threads start to spawn. All of them seem to hang on `/karafka-rdkafka-0.15.1/lib/rdkafka/native_kafka.rb:53:in 'rd_kafka_poll'`. After a couple of minutes there were 4 of them already. Haven't had a chance to look into rdkafka, therefore not sure if this growth is expected.

**Comment by mensfeld** [comment]
Works correctly. Here's a minimal setup (unless you did something else) minus the noise:

```ruby
producer = ::WaterDrop::Producer.new do |wd_config|
 # something incorrect
 wd_config.kafka[:'bootstrap.servers'] = '0.0.0.0:29092'
 wd_config.kafka[:'transactional.id'] = SecureRandom.hex(6)
 # Make shorter to timeout faster
 wd_config.kafka[:'message.timeout.ms'] = 2_000
 wd_config.kafka[:'transaction.timeout.ms'] = 3_000
end

producer.monitor.subscribe(WaterDrop::Instrumentation::LoggerListener.new(Logger.new(STDOUT)))

producer.produce_many_sync([{ topic: '4c28211d4684', payload: 'a' }])
```

here are logs:

```ruby
E, [2024-06-06T13:28:12.234512 #2347228] ERROR -- : [waterdrop-32f7954face5] Error occurred: Local: Timed out (timed_out) - transaction.begin
E, [2024-06-06T13:28:19.235389 #2347228] ERROR -- : [waterdrop-32f7954face5] Error occurred: Local: Timed out (timed_out) - transaction.begin
E, [2024-06-06T13:28:26.736377 #2347228] ERROR -- : [waterdrop-32f7954face5] Error occurred: Local: Timed out (timed_out) - transaction.begin
E, [2024-06-06T13:28:34.737464 #2347228] ERROR -- : [waterdrop-32f7954face5] Error occurred: Local: Timed out (timed_out) - transaction.begin
E, [2024-06-06T13:28:40.738384 #2347228] ERROR -- : [waterdrop-32f7954face5] Error occurred: Local: Timed out (timed_out) - transaction.abort
E, [2024-06-06T13:28:47.239256 #2347228] ERROR -- : [waterdrop-32f7954face5] Error occurred: Local: Timed out (timed_out) - transaction.abort
E, [2024-06-06T13:28:54.240035 #2347228] ERROR -- : [waterdrop-32f7954face5] Error occurred: Local: Timed out (timed_out) - transaction.abort
E, [2024-06-06T13:29:01.740825 #2347228] ERROR -- : [waterdrop-32f7954face5] Error occurred: Local: Timed out (timed_out) - transaction.abort
E, [2024-06-06T13:29:09.741818 #2347228] ERROR -- : [waterdrop-32f7954face5] Error occurred: Local: Timed out (timed_out) - transaction.abort
E, [2024-06-06T13:29:09.741982 #2347228] ERROR -- : [waterdrop-32f7954face5] Error occurred: #<Rdkafka::RdkafkaError: Local: Timed out (timed_out)> - messages.produce_many_sync
(irb):12:in `<main>': #<Rdkafka::RdkafkaError: Local: Timed out (timed_out)> (WaterDrop::Errors::ProduceManyError)

```

**Comment by mensfeld** [comment]
The thing that is NOT working here is the fact that the timeout should raise faster on retried transacitonal operations because reaching the timeout time. This however could cause consistency issues on retryable transactions hence I am leading towards documenting this rather than trying to re-raise on wait timeout time.

**Comment by mensfeld** [comment]
you can see this if you run it like that (should timeout after 1 second, times out much later):

```
producer = ::WaterDrop::Producer.new do |wd_config|
 # wd_config.kafka[:'bootstrap.servers'] = '0.0.0.0:29092'
 wd_config.kafka[:'transactional.id'] = SecureRandom.hex(6)
##  wd_config.kafka[:'max.in.flight'] = 5
 wd_config.kafka[:'message.timeout.ms'] = 2_000
 wd_config.kafka[:'transaction.timeout.ms'] = 3_000
 wd_config.max_attempts_on_transaction_command = 1
 wd_config.wait_backoff_on_transaction_command = 5
 wd_config.max_wait_timeout = 1_000
end

producer.monitor.subscribe(WaterDrop::Instrumentation::LoggerListener.new(Logger.new(STDOUT)))

producer.produce_many_sync([{ topic: '4c28211d4684', payload: 'a' }])

```

**Comment by mensfeld** [comment]
@Aerdayne if you can confirm this is the case I will look into this deeper.

**Comment by Aerdayne** [comment]
Can confirm that both of your versions with adjusted timeout values raise eventually.

**Comment by mensfeld** [comment]
@Aerdayne ok, so it is not hanging. It just retries and (aside from time it takes) works as expected. I will document this behaviour. I do not want to have granular time tracking inside of transactions because this could cause really weird problems (especially if not able to abort) causing problems with LSO.

**Comment by mensfeld** [comment]
I will close this issue once documented.

**Comment by mensfeld** [comment]
added a warning in the timeout section: http://localhost/docs/WaterDrop-Transactions/#timeouts
