### ISSUE TITLE
NoMethodError: undefined method `init_transactions' if `transactional.id` is specified

### ISSUE THREAD

**Issue by eugene-nikolaev** [karafka/waterdrop#527]
Hi!

Waterdrop 2.6.14
Ruby 2.7.5

produce_many_sync while `transaction.id` specified leads to an exception:

```
Caused by:                                                                                                                                                                                                      │
│ NoMethodError: undefined method `init_transactions' for #<Rdkafka::Producer:0x00007f4af8ec9128>                                                                                                                 │
│ /usr/local/bundle/gems/waterdrop-2.6.14/lib/waterdrop/clients/rdkafka.rb:27:in `new'                                                                                                                            │
│ /usr/local/bundle/gems/waterdrop-2.6.14/lib/waterdrop/producer/builder.rb:19:in `call'                                                                                                                          │
│ /usr/local/bundle/gems/waterdrop-2.6.14/lib/waterdrop/producer.rb:105:in `block in client'                                                                                                                      │
│ /usr/local/bundle/gems/waterdrop-2.6.14/lib/waterdrop/producer.rb:82:in `synchronize'                                                                                                                           │
│ /usr/local/bundle/gems/waterdrop-2.6.14/lib/waterdrop/producer.rb:82:in `client'                                                                                                                                │
│ /usr/local/bundle/gems/waterdrop-2.6.14/lib/waterdrop/producer/transactions.rb:59:in `block (4 levels) in transaction'                                                                                          │
│ /usr/local/bundle/gems/karafka-core-2.3.0/lib/karafka/core/monitoring/notifications.rb:122:in `measure_time_taken'                                                                                              │
│ /usr/local/bundle/gems/karafka-core-2.3.0/lib/karafka/core/monitoring/notifications.rb:98:in `instrument'                                                                                                       │
│ /usr/local/bundle/gems/karafka-core-2.3.0/lib/karafka/core/monitoring/monitor.rb:34:in `instrument'                                                                                                             │
│ /usr/local/bundle/gems/waterdrop-2.6.14/lib/waterdrop/producer/transactions.rb:159:in `transactional_instrument'                                                                                                │
│ /usr/local/bundle/gems/waterdrop-2.6.14/lib/waterdrop/producer/transactions.rb:59:in `block (3 levels) in transaction'                                                                                          │
│ /usr/local/bundle/gems/waterdrop-2.6.14/lib/waterdrop/producer/transactions.rb:181:in `with_transactional_error_handling'                                                                                       │
│ /usr/local/bundle/gems/waterdrop-2.6.14/lib/waterdrop/producer/transactions.rb:58:in `block (2 levels) in transaction'                                                                                          │
│ /usr/local/bundle/gems/karafka-core-2.3.0/lib/karafka/core/monitoring/notifications.rb:122:in `measure_time_taken'                                                                                              │
│ /usr/local/bundle/gems/karafka-core-2.3.0/lib/karafka/core/monitoring/notifications.rb:98:in `instrument'                                                                                                       │
│ /usr/local/bundle/gems/karafka-core-2.3.0/lib/karafka/core/monitoring/monitor.rb:34:in `instrument'                                                                                                             │
│ /usr/local/bundle/gems/waterdrop-2.6.14/lib/waterdrop/producer/transactions.rb:159:in `transactional_instrument'                                                                                                │
│ /usr/local/bundle/gems/waterdrop-2.6.14/lib/waterdrop/producer/transactions.rb:57:in `block in transaction'                                                                                                     │
│ /usr/local/bundle/gems/waterdrop-2.6.14/lib/waterdrop/producer/transactions.rb:56:in `synchronize'                                                                                                              │
│ /usr/local/bundle/gems/waterdrop-2.6.14/lib/waterdrop/producer/transactions.rb:56:in `transaction'                                                                                                              │
│ /usr/local/bundle/gems/waterdrop-2.6.14/lib/waterdrop/producer/transactions.rb:150:in `with_transaction_if_transactional'                                                                                       │
│ /usr/local/bundle/gems/waterdrop-2.6.14/lib/waterdrop/producer/sync.rb:66:in `block in produce_many_sync'                                                                                                       │
│ /usr/local/bundle/gems/karafka-core-2.3.0/lib/karafka/core/monitoring/notifications.rb:122:in `measure_time_taken'                                                                                              │
│ /usr/local/bundle/gems/karafka-core-2.3.0/lib/karafka/core/monitoring/notifications.rb:98:in `instrument'                                                                                                       │
│ /usr/local/bundle/gems/karafka-core-2.3.0/lib/karafka/core/monitoring/monitor.rb:34:in `instrument'                                                                                                             │
│ /usr/local/bundle/gems/waterdrop-2.6.14/lib/waterdrop/producer/sync.rb:65:in `produce_many_sync'                                                                                                                <skipped>  
```

So, the config tries to call the `init_transactions` method which isn't in `rdkafka-ruby`'s producer:

https://github.com/karafka/waterdrop/blob/2748edf62cc4f292e105d15e5d9088db8ec008c2/lib/waterdrop/clients/rdkafka.rb#L57

**Comment by mensfeld** [comment]
What `karafka-rdkafka` version is that?

**Comment by eugene-nikolaev** [comment]
`karafka-rdkafka-0.14.11`

**Comment by mensfeld** [comment]
1. not supported ruby
2. outdated waterdrop
3. outdated core
4. outdated karafka-rdkafka

nothing to do for me here :wave:
